# Generated by Django 6.0.5 on 2026-05-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0002_product_dosages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SupplierPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Наиболее предпочтительный'), (2, 'Среднее предпочтение'), (3, 'Наименее предпочтительный')], verbose_name='Рейтинг предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_preferences', to='pharmacy.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_preferences', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Предпочтение поставщика',
                'verbose_name_plural': 'Предпочтения поставщиков',
                'unique_together': {('product', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('dosage', models.CharField(max_length=100, verbose_name='Фасовка')),
                ('supplier_quantity', models.IntegerField(default=0, verbose_name='Количество у поставщика')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена поставщика')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
                'unique_together': {('supplier', 'product_name', 'dosage')},
            },
        ),
    ]
