# Generated by Django 6.0.5 on 2026-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
