# Generated by Django 6.0.5 on 2026-05-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierproduct_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Наиболее предпочтительный'), (2, 'Среднее предпочтение'), (3, 'Наименее предпочтительный')], default=3, verbose_name='Рейтинг'),
        ),
    ]
