# Generated by Django 6.0.5 on 2026-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosages',
            field=models.JSONField(default=list, verbose_name='Фасовки (дозировки)'),
        ),
    ]
